/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankinggui;

import javax.swing.JOptionPane;

/**
 *
 * @author fragger
 */
public class BalanceTransferForm extends javax.swing.JFrame {

    /**
     * Creates new form BalanceTransferForm
     */
    public BalanceTransferForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        proceedButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        transferAmtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        receiverAccNoField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pinField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(435, 335));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Balance Transfer Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 150, 30));

        proceedButton.setText("Proceed Transfer");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });
        jPanel1.add(proceedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, 30));

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Authorize");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 20));

        transferAmtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferAmtFieldMouseClicked(evt);
            }
        });
        transferAmtField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                transferAmtFieldMouseMoved(evt);
            }
        });
        transferAmtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmtFieldActionPerformed(evt);
            }
        });
        transferAmtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                transferAmtFieldKeyTyped(evt);
            }
        });
        jPanel1.add(transferAmtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, 20));

        jLabel4.setText("PIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Transfer To");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 20));

        jLabel6.setText("Account Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 20));

        receiverAccNoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiverAccNoFieldMouseClicked(evt);
            }
        });
        receiverAccNoField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                receiverAccNoFieldMouseMoved(evt);
            }
        });
        receiverAccNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverAccNoFieldActionPerformed(evt);
            }
        });
        receiverAccNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                receiverAccNoFieldKeyTyped(evt);
            }
        });
        jPanel1.add(receiverAccNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Amount Details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 20));

        jLabel8.setText("Transfer Amount");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 20));

        pinField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinFieldMouseClicked(evt);
            }
        });
        pinField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pinFieldMouseMoved(evt);
            }
        });
        pinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinFieldActionPerformed(evt);
            }
        });
        pinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinFieldKeyTyped(evt);
            }
        });
        jPanel1.add(pinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
       User.auxUser = new SqlHandler();
        if(new String(receiverAccNoField.getText()).equals(""))
        {
            getToolkit().beep();
        }
        else if(User.auxUser.matchAccNumber(new String(receiverAccNoField.getText())))
        {
            String pin = new String(pinField.getPassword());
            if(pin.equals(""))
            {
                getToolkit().beep();
            }
            else if(User.curUser.matchPin(User.encodePin(pin)))
            {
                if(new String(transferAmtField.getText()).equals(""))
                {
                    getToolkit().beep();
                }
                else if(SqlHandler.balTransfer(User.curUser,User.auxUser, Integer.parseInt(new String(transferAmtField.getText()))))
                {
                    JOptionPane.showInputDialog(rootPane, "Transfer Successful !","The amount has been transferred to given account!");
                    this.dispose();
                }
                else
                {
                    getToolkit().beep();
                    JOptionPane.showInputDialog(rootPane, "Insufficient Balance !","You do not have sufficient balance for this txn");
                    transferAmtField.setText("");
                    
                }
            }
            else
            {
                getToolkit().beep();
                JOptionPane.showInputDialog(rootPane, "Incorrect PIN !");
                pinField.setText("");
            }
        }
        else
        {
            getToolkit().beep();
            JOptionPane.showInputDialog(rootPane, "Check account number !","Given account does not exist!");
            receiverAccNoField.setText("");
        }
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        this.dispose();        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void transferAmtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferAmtFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmtFieldMouseClicked

    private void transferAmtFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferAmtFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmtFieldMouseMoved

    private void transferAmtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmtFieldActionPerformed

    private void transferAmtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transferAmtFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_transferAmtFieldKeyTyped

    private void receiverAccNoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiverAccNoFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverAccNoFieldMouseClicked

    private void receiverAccNoFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiverAccNoFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverAccNoFieldMouseMoved

    private void receiverAccNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverAccNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverAccNoFieldActionPerformed

    private void receiverAccNoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiverAccNoFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverAccNoFieldKeyTyped

    private void pinFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldMouseClicked

    private void pinFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldMouseMoved

    private void pinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldActionPerformed

    private void pinFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }

        else if(new String(pinField.getText()).length()==4)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pinFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceTransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceTransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceTransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceTransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceTransferForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JButton proceedButton;
    private javax.swing.JTextField receiverAccNoField;
    private javax.swing.JTextField transferAmtField;
    // End of variables declaration//GEN-END:variables
}
