/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankinggui;

import javax.swing.JOptionPane;

/**
 *
 * @author fragger
 */
public class DepositFrame extends javax.swing.JFrame {

    /**
     * Creates new form DepositFrame
     */
    public DepositFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositSuccessDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        depositSuccessLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        depositAmtField = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();

        depositSuccessDialog.setAlwaysOnTop(true);
        depositSuccessDialog.setLocationByPlatform(true);
        depositSuccessDialog.setMinimumSize(new java.awt.Dimension(280, 190));
        depositSuccessDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depositSuccessLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        depositSuccessLabel.setText("You balance is now :      ");
        jPanel2.add(depositSuccessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 180, 20));

        jLabel4.setText("Deposit Done Successfully !");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        depositSuccessDialog.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 150));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(276, 224));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Deposit Form");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, 30));

        jLabel3.setText("Amount : ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 70, 20));

        depositAmtField.setText("0");
        depositAmtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositAmtFieldMouseClicked(evt);
            }
        });
        depositAmtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                depositAmtFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                depositAmtFieldKeyTyped(evt);
            }
        });
        jPanel3.add(depositAmtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, -1));

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        jPanel3.add(depositButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositAmtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositAmtFieldMouseClicked
        depositAmtField.setText("");
    }//GEN-LAST:event_depositAmtFieldMouseClicked

    private void depositAmtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositAmtFieldKeyPressed

    }//GEN-LAST:event_depositAmtFieldKeyPressed

    private void depositAmtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositAmtFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }       
    }//GEN-LAST:event_depositAmtFieldKeyTyped

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        if(Integer.parseInt(depositAmtField.getText())<=0)
        {
            JOptionPane.showInputDialog(rootPane, "WARNING!","Please enter a valid amount !");
        }
        
        else
        {
        User.curUser.deposit(Integer.parseInt(new String(depositAmtField.getText())));
        this.dispose();
        depositSuccessLabel.setText("Your balance is now : "+User.curUser.getBal());
        depositSuccessDialog.setVisible(true);
        }
    }//GEN-LAST:event_depositButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        depositSuccessDialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField depositAmtField;
    private javax.swing.JButton depositButton;
    private javax.swing.JDialog depositSuccessDialog;
    private javax.swing.JLabel depositSuccessLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
