/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankinggui;

/**
 *
 * @author fragger
 */
public class ForgotFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotFrame
     */
    public ForgotFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        incorrectAnswerDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tryAgainButton = new javax.swing.JButton();
        resetPinDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        resetPinButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        newPinConfirmField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        newPinField = new javax.swing.JPasswordField();
        resetPinSuccessDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        securityQField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        securityAField = new javax.swing.JPasswordField();
        verifyButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        incorrectAnswerDialog.setAlwaysOnTop(true);
        incorrectAnswerDialog.setLocationByPlatform(true);
        incorrectAnswerDialog.setMinimumSize(new java.awt.Dimension(220, 150));
        incorrectAnswerDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Answer did not match !");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 20));

        tryAgainButton.setText("Try Again?");
        tryAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryAgainButtonActionPerformed(evt);
            }
        });
        jPanel4.add(tryAgainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        incorrectAnswerDialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        resetPinDialog.setAlwaysOnTop(true);
        resetPinDialog.setLocationByPlatform(true);
        resetPinDialog.setMinimumSize(new java.awt.Dimension(325, 275));
        resetPinDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("RESET PIN FORM");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 20));

        resetPinButton.setText("Reset PIN");
        resetPinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPinButtonActionPerformed(evt);
            }
        });
        jPanel5.add(resetPinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel8.setText("Confirm New PIN : ");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 20));

        newPinConfirmField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPinConfirmFieldKeyTyped(evt);
            }
        });
        jPanel5.add(newPinConfirmField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, -1));

        jLabel10.setText("New PIN : ");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 20));

        newPinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPinFieldKeyTyped(evt);
            }
        });
        jPanel5.add(newPinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, -1));

        resetPinDialog.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 220));

        resetPinSuccessDialog.setAlwaysOnTop(true);
        resetPinSuccessDialog.setLocationByPlatform(true);
        resetPinSuccessDialog.setMinimumSize(new java.awt.Dimension(260, 180));
        resetPinSuccessDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("PIN changed successfully !");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, 20));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel6.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        resetPinSuccessDialog.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 140));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forgot PIN");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(410, 280));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Forgot PIN Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 30));

        jLabel2.setText("Question");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, 20));

        securityQField.setEditable(false);
        securityQField.setText(User.curUser.securityQ);
        jPanel1.add(securityQField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 290, 20));

        jLabel3.setText("Please Answer your Security Question");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel4.setText("Answer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 20));
        jPanel1.add(securityAField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 140, -1));

        verifyButton.setText("Verify");
        verifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(verifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 90, -1));

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 200, 70, -1));

        jLabel5.setText("Account Number : "+User.curUser.getAccNo());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void verifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyButtonActionPerformed
       if(User.curUser.matchSecurityA(User.encodeSecurityA(new String(securityAField.getPassword()))))
       {
           resetPinDialog.setVisible(true);
       }
       else
       {
            incorrectAnswerDialog.setVisible(true);
       }
    }//GEN-LAST:event_verifyButtonActionPerformed

    private void tryAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryAgainButtonActionPerformed
        incorrectAnswerDialog.dispose();
        securityAField.setText("");
    }//GEN-LAST:event_tryAgainButtonActionPerformed

    private void resetPinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPinButtonActionPerformed
       if(new String(newPinField.getPassword()).equals(new String(newPinConfirmField.getPassword())))
       {
          User.curUser.setPin(User.encodePin(new String(newPinField.getPassword())));
          User.curUser.setAttempts(User.MAXATTEMPTS);
          User.curUser.setLock(false);
          this.dispose();
          resetPinSuccessDialog.setVisible(true);
          
       }
       else
       {
           getToolkit().beep();
           newPinField.setText("");
           newPinConfirmField.setText("");
       }
    }//GEN-LAST:event_resetPinButtonActionPerformed

    private void newPinFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPinFieldKeyTyped
          char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }      
        
        else if(new String(newPinField.getText()).length()==4)
        {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_newPinFieldKeyTyped

    private void newPinConfirmFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPinConfirmFieldKeyTyped
          char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }      
        
        else if(new String(newPinConfirmField.getText()).length()==4)
        {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_newPinConfirmFieldKeyTyped

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        resetPinSuccessDialog.dispose();
        resetPinDialog.dispose();
        
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JDialog incorrectAnswerDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField newPinConfirmField;
    private javax.swing.JPasswordField newPinField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton resetPinButton;
    private javax.swing.JDialog resetPinDialog;
    private javax.swing.JDialog resetPinSuccessDialog;
    private javax.swing.JPasswordField securityAField;
    private javax.swing.JTextField securityQField;
    private javax.swing.JButton tryAgainButton;
    private javax.swing.JButton verifyButton;
    // End of variables declaration//GEN-END:variables
}
