/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankinggui;

/**
 *
 * @author fragger
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notFoundDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tryAgainButton = new javax.swing.JButton();
        loginAccountDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        accNoField = new javax.swing.JTextField();
        checkAccountButton = new javax.swing.JButton();
        resetButton1 = new javax.swing.JButton();
        lockedNotifDialog = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        forgotButton1 = new javax.swing.JButton();
        homeButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        forgotAccountVerifyDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        accNoForgotField = new javax.swing.JTextField();
        checkAccountForgotButton = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();
        aboutDialog = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        createNewAccountButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        transactionButton = new javax.swing.JButton();
        forgotButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Help = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        notFoundDialog.setAlwaysOnTop(true);
        notFoundDialog.setLocationByPlatform(true);
        notFoundDialog.setMinimumSize(new java.awt.Dimension(230, 130));
        notFoundDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Account Number doesn't exist!");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, 190, -1));

        tryAgainButton.setText("Try Again?");
        tryAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryAgainButtonActionPerformed(evt);
            }
        });
        jPanel4.add(tryAgainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        notFoundDialog.getContentPane().add(jPanel4, new java.awt.GridBagConstraints());

        loginAccountDialog.setAlwaysOnTop(true);
        loginAccountDialog.setFocusCycleRoot(false);
        loginAccountDialog.setFocusTraversalPolicyProvider(true);
        loginAccountDialog.setLocationByPlatform(true);
        loginAccountDialog.setMinimumSize(new java.awt.Dimension(290, 150));
        loginAccountDialog.setResizable(false);
        loginAccountDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Account Number");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 20));

        accNoField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accNoFieldMouseClicked(evt);
            }
        });
        accNoField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                accNoFieldMouseMoved(evt);
            }
        });
        accNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoFieldActionPerformed(evt);
            }
        });
        accNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accNoFieldKeyTyped(evt);
            }
        });
        jPanel5.add(accNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 20));

        checkAccountButton.setText("Check Account");
        checkAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAccountButtonActionPerformed(evt);
            }
        });
        jPanel5.add(checkAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        resetButton1.setText("Reset");
        resetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(resetButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, -1));

        loginAccountDialog.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 130));

        lockedNotifDialog.setAlwaysOnTop(true);
        lockedNotifDialog.setLocationByPlatform(true);
        lockedNotifDialog.setMinimumSize(new java.awt.Dimension(350, 190));
        lockedNotifDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forgotButton1.setText("Unlock");
        forgotButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(forgotButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 80, -1));

        homeButton1.setText("Home");
        homeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(homeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel8.setText("Your account is locked for security reasons!");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 30));

        lockedNotifDialog.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 330, 160));

        forgotAccountVerifyDialog.setAlwaysOnTop(true);
        forgotAccountVerifyDialog.setFocusCycleRoot(false);
        forgotAccountVerifyDialog.setFocusTraversalPolicyProvider(true);
        forgotAccountVerifyDialog.setLocationByPlatform(true);
        forgotAccountVerifyDialog.setMinimumSize(new java.awt.Dimension(290, 150));
        forgotAccountVerifyDialog.setResizable(false);
        forgotAccountVerifyDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Account Number");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 20));

        accNoForgotField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accNoForgotFieldMouseClicked(evt);
            }
        });
        accNoForgotField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                accNoForgotFieldMouseMoved(evt);
            }
        });
        accNoForgotField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accNoForgotFieldActionPerformed(evt);
            }
        });
        accNoForgotField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accNoForgotFieldKeyTyped(evt);
            }
        });
        jPanel6.add(accNoForgotField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 20));

        checkAccountForgotButton.setText("Check Account");
        checkAccountForgotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAccountForgotButtonActionPerformed(evt);
            }
        });
        jPanel6.add(checkAccountForgotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        resetButton2.setText("Reset");
        resetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(resetButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, -1));

        forgotAccountVerifyDialog.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 130));

        aboutDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        aboutDialog.setAlwaysOnTop(true);
        aboutDialog.setFocusCycleRoot(false);
        aboutDialog.setFocusTraversalPolicyProvider(true);
        aboutDialog.setLocationByPlatform(true);
        aboutDialog.setMinimumSize(new java.awt.Dimension(400, 320));
        aboutDialog.setResizable(false);
        aboutDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "About"));
        jPanel9.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setText("About");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 20));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel13.setText("Banking App");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 40, 80, 20));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("hey there!\nThis app is developed by Shashank Singh.\n\nContact : ssinghmy@gmail.com");
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 100));

        aboutDialog.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 240));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)), "New Account Setup", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createNewAccountButton.setText("Create new Account");
        createNewAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createNewAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewAccountButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createNewAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 30));

        jLabel4.setText("Want a new Account?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 30));

        jLabel11.setText("Click Here");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 240, 240));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Welcome to Banking App of "+User.bankName);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 410, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText(User.bankName);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 280, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)), "Account Holders", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transactionButton.setText("Do a Transaction");
        transactionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionButtonActionPerformed(evt);
            }
        });
        jPanel2.add(transactionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 180, 40));

        forgotButton.setText("Forgot Pin ?");
        forgotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotButtonActionPerformed(evt);
            }
        });
        jPanel2.add(forgotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 30));

        jLabel3.setText("Locked your account? Click here");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 240, 240));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("developed by Shashank Singh");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        Help.setText("Help");

        jMenuItem1.setText("Help");
        Help.add(jMenuItem1);

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        Help.add(About);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tryAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryAgainButtonActionPerformed
      notFoundDialog.dispose();
    }//GEN-LAST:event_tryAgainButtonActionPerformed

    private void accNoFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accNoFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoFieldMouseClicked

    private void accNoFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accNoFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoFieldMouseMoved

    private void accNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoFieldActionPerformed

    private void resetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButton1ActionPerformed

    private void checkAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAccountButtonActionPerformed
        User.curUser = new SqlHandler();
        if(User.curUser.matchAccNumber(new String(accNoField.getText())))
        {
            if(User.curUser.lockState()
                    )
            {
                loginAccountDialog.dispose();
                lockedNotifDialog.setVisible(true);
              
            }
            else
            {
            loginAccountDialog.dispose();
            this.dispose();
            new VerifyPwdFrame().setVisible(true);
            }
        }
        else
        {
            accNoField.setText("");
            notFoundDialog.setVisible(true);
        }
    }//GEN-LAST:event_checkAccountButtonActionPerformed

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionButtonActionPerformed
        accNoField.setText("");
        loginAccountDialog.setVisible(true);
    }//GEN-LAST:event_transactionButtonActionPerformed

    private void forgotButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotButton1ActionPerformed
       this.dispose();
        lockedNotifDialog.dispose();
       new ForgotFrame().setVisible(true);
    }//GEN-LAST:event_forgotButton1ActionPerformed

    private void homeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton1ActionPerformed
       lockedNotifDialog.dispose();
    }//GEN-LAST:event_homeButton1ActionPerformed

    private void accNoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accNoFieldKeyTyped
              char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }       

    }//GEN-LAST:event_accNoFieldKeyTyped

    private void forgotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotButtonActionPerformed
        //this.dispose();
        forgotAccountVerifyDialog.setVisible(true);
    }//GEN-LAST:event_forgotButtonActionPerformed

    private void accNoForgotFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accNoForgotFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoForgotFieldMouseClicked

    private void accNoForgotFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accNoForgotFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoForgotFieldMouseMoved

    private void accNoForgotFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accNoForgotFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accNoForgotFieldActionPerformed

    private void accNoForgotFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accNoForgotFieldKeyTyped
     char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }       
    }//GEN-LAST:event_accNoForgotFieldKeyTyped

    private void checkAccountForgotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAccountForgotButtonActionPerformed
         User.curUser = new SqlHandler();
        if(User.curUser.matchAccNumber(new String(accNoForgotField.getText())))
        {
           forgotAccountVerifyDialog.dispose();
           new ForgotFrame().setVisible(true);
        }
        else
        {
            notFoundDialog.setVisible(true);
        }
    }//GEN-LAST:event_checkAccountForgotButtonActionPerformed

    private void resetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButton2ActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void createNewAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewAccountButtonActionPerformed
       new NewAccountFrame().setVisible(true);
    }//GEN-LAST:event_createNewAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenu Help;
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JTextField accNoField;
    private javax.swing.JTextField accNoForgotField;
    private javax.swing.JButton checkAccountButton;
    private javax.swing.JButton checkAccountForgotButton;
    private javax.swing.JButton createNewAccountButton;
    private javax.swing.JDialog forgotAccountVerifyDialog;
    private javax.swing.JButton forgotButton;
    private javax.swing.JButton forgotButton1;
    private javax.swing.JButton homeButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JDialog lockedNotifDialog;
    private javax.swing.JDialog loginAccountDialog;
    private javax.swing.JDialog notFoundDialog;
    private javax.swing.JButton resetButton1;
    private javax.swing.JButton resetButton2;
    private javax.swing.JButton transactionButton;
    private javax.swing.JButton tryAgainButton;
    // End of variables declaration//GEN-END:variables
}
