/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankinggui;

import javax.swing.JOptionPane;
/**
 *
 * @author fragger
 */
public class NewAccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewAccountFrame
     */
    public NewAccountFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accNoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressField3 = new javax.swing.JTextField();
        addressField1 = new javax.swing.JTextField();
        addressField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dobField = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        pinGenerateButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pinField = new javax.swing.JPasswordField();
        securityAShowButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        openingBalField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        termsCheckBox = new javax.swing.JCheckBox();
        submitButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        genderDropDown = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        maritalStatusDropDown = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        securityQField = new javax.swing.JTextField();
        securityAField = new javax.swing.JPasswordField();
        pinShowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(675, 530));
        setPreferredSize(new java.awt.Dimension(640, 480));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SignUp"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Sign Up - Create your account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Account Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        accNoField.setEditable(false);
        accNoField.setText(User.generateAccNo());
        jPanel1.add(accNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 80, -1));

        jLabel3.setText("Name *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, -1));

        jLabel4.setText("Address Line 3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 110, 20));
        jPanel1.add(addressField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, 20));

        addressField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressField1ActionPerformed(evt);
            }
        });
        jPanel1.add(addressField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 120, 20));
        jPanel1.add(addressField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 120, 20));

        jLabel5.setText("Address Line 1 *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 20));

        jLabel6.setText("Address Line 2 *");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 110, 20));

        jLabel7.setText("Date Of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));

        dobField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobFieldKeyTyped(evt);
            }
        });
        jPanel1.add(dobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, -1));

        jLabel8.setText("(dd/mm/yy)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 20));

        pinGenerateButton.setText("Generate PIN");
        pinGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinGenerateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pinGenerateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 110, 20));

        jLabel9.setText("PIN");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 30, 20));

        pinField.setEchoChar('*');
        pinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinFieldKeyTyped(evt);
            }
        });
        jPanel1.add(pinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 70, 20));

        securityAShowButton.setText("Show");
        securityAShowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                securityAShowButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                securityAShowButtonMouseReleased(evt);
            }
        });
        securityAShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityAShowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(securityAShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 70, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Account");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 20));

        jLabel11.setText("Opening Balance");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 20));

        openingBalField.setText("1000");
        openingBalField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openingBalFieldMouseClicked(evt);
            }
        });
        openingBalField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                openingBalFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                openingBalFieldKeyTyped(evt);
            }
        });
        jPanel1.add(openingBalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 620, 10));

        termsCheckBox.setText("I agree with the T & C of the bank");
        jPanel1.add(termsCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jLabel12.setText("Gender *");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 60, 20));

        genderDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "M", "F" }));
        genderDropDown.setToolTipText("");
        genderDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderDropDownActionPerformed(evt);
            }
        });
        jPanel1.add(genderDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 50, -1));

        jLabel13.setText("Marital Status * ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, 20));

        maritalStatusDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Unmarried", "Married" }));
        jPanel1.add(maritalStatusDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("In case you lose it !");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, 30));

        jLabel15.setText("Security Answer   : ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, 20));

        jLabel16.setText("Security Question : ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 110, 20));
        jPanel1.add(securityQField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 130, -1));

        securityAField.setEchoChar('*');
        jPanel1.add(securityAField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, -1));

        pinShowButton.setText("Show");
        pinShowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pinShowButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pinShowButtonMouseReleased(evt);
            }
        });
        pinShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinShowButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pinShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 70, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void addressField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressField1ActionPerformed

    private void securityAShowButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_securityAShowButtonMousePressed
      securityAField.setEchoChar((char)0);
    }//GEN-LAST:event_securityAShowButtonMousePressed

    private void securityAShowButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_securityAShowButtonMouseReleased
       securityAField.setEchoChar('*');
    }//GEN-LAST:event_securityAShowButtonMouseReleased

    private void pinGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinGenerateButtonActionPerformed
       String pin = User.generatePin();
       pinField.setText(pin);
    }//GEN-LAST:event_pinGenerateButtonActionPerformed

    private void securityAShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityAShowButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityAShowButtonActionPerformed

    private void openingBalFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openingBalFieldMouseClicked
        openingBalField.setText("");
    }//GEN-LAST:event_openingBalFieldMouseClicked

    private void openingBalFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openingBalFieldKeyPressed

    }//GEN-LAST:event_openingBalFieldKeyPressed

    private void openingBalFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openingBalFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_openingBalFieldKeyTyped

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='a') && (c<='z') || (c>='A' &&c<='Z') || (c==' ') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
         
    }//GEN-LAST:event_nameFieldKeyTyped

    private void dobFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobFieldKeyTyped
         char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c=='/') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
        else if(new String(dobField.getText()).length()==8)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_dobFieldKeyTyped

    private void pinFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c=='/') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
        else if(new String(pinField.getText()).length()==4)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pinFieldKeyTyped

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
    boolean check = true;
    
    if(nameField.getText().length()==0)
        check=false;
    else if(dobField.getText().length()==0)
        check=false;
    else if(openingBalField.getText().length()==0)
        check=false;
    else if(dobField.getText().length()==0)
        check=false;
    else if(securityQField.getText().length()==0)
        check = false;
    else if ((new String(securityAField.getPassword()).length()==0))
        check = false;
    else if((new String(pinField.getPassword()).length())==0)
        check=false;
    else if(addressField1.getText().length()==0)
        check=false;
    else if(addressField2.getText().length()==0)
        check=false;
    else if(genderDropDown.getSelectedIndex()==0)
        check=false;
    else if(maritalStatusDropDown.getSelectedIndex()==0)
        check=false;
    
        if(!check)
        {
            getToolkit().beep();
            JOptionPane.showInputDialog(rootPane, "Entries not valid!","Please verify the entries");     
        }
        else if(!termsCheckBox.isSelected())
        {
            getToolkit().beep();
            JOptionPane.showInputDialog(rootPane, "Terms and Conditions!","Please accept our terms and conditions!");
        }
        else
        {
            String gender;
            boolean maritalStatus;
                if(maritalStatusDropDown.getSelectedIndex()==1) maritalStatus = false;
                else maritalStatus = true;
            
                if(genderDropDown.getSelectedIndex()==1) gender="M";
                else gender = "F";
                
            if(SqlHandler.writeRecord(accNoField.getText(), nameField.getText(), Float.parseFloat(openingBalField.getText()), 
                    User.encodePin(new String(pinField.getPassword())), securityQField.getText(), 
                    User.encodeSecurityA(new String(securityAField.getPassword())), gender, maritalStatus, 
                    dobField.getText(), addressField1.getText(), addressField2.getText(), addressField3.getText()))
            {
                JOptionPane.showInputDialog(rootPane, "Successful !", "Enjoy banking with us !");
                this.dispose();
            }
            else
            {
                JOptionPane.showInputDialog(rootPane, "SQL Error", "Problem with Table Creation. Contact developer.");
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void genderDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderDropDownActionPerformed

    private void pinShowButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinShowButtonMousePressed
        pinField.setEchoChar((char)0);
    }//GEN-LAST:event_pinShowButtonMousePressed

    private void pinShowButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinShowButtonMouseReleased
       pinField.setEchoChar('*');
    }//GEN-LAST:event_pinShowButtonMouseReleased

    private void pinShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinShowButtonActionPerformed
       pinField.setEchoChar((char)0);
    }//GEN-LAST:event_pinShowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccountFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accNoField;
    private javax.swing.JTextField addressField1;
    private javax.swing.JTextField addressField2;
    private javax.swing.JTextField addressField3;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JComboBox genderDropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox maritalStatusDropDown;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField openingBalField;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JButton pinGenerateButton;
    private javax.swing.JButton pinShowButton;
    private javax.swing.JPasswordField securityAField;
    private javax.swing.JButton securityAShowButton;
    private javax.swing.JTextField securityQField;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox termsCheckBox;
    // End of variables declaration//GEN-END:variables
}
