/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankinggui;

/**
 *
 * @author fragger
 */
public class VerifyPwdFrame extends javax.swing.JFrame {

    /**
     * Creates new form VerifyPwdFrame
     */
    public VerifyPwdFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwdIncorrectDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tryAgainButton = new javax.swing.JButton();
        exceedMaxAttemptDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        unlockButton = new javax.swing.JButton();
        homeButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        checkPinButton = new javax.swing.JButton();
        pinField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        resetButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        pwdIncorrectDialog.setAlwaysOnTop(true);
        pwdIncorrectDialog.setLocationByPlatform(true);
        pwdIncorrectDialog.setMinimumSize(new java.awt.Dimension(230, 130));
        pwdIncorrectDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Wrong Pin Entered !");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, 190, -1));

        tryAgainButton.setText("Try Again?");
        tryAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryAgainButtonActionPerformed(evt);
            }
        });
        jPanel4.add(tryAgainButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        pwdIncorrectDialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 150));

        exceedMaxAttemptDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        exceedMaxAttemptDialog.setAlwaysOnTop(true);
        exceedMaxAttemptDialog.setLocationByPlatform(true);
        exceedMaxAttemptDialog.setMinimumSize(new java.awt.Dimension(250, 163));
        exceedMaxAttemptDialog.setPreferredSize(new java.awt.Dimension(230, 170));
        exceedMaxAttemptDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Reason : Exceeded max login attempts");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 20));

        unlockButton.setText("Unlock");
        unlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockButtonActionPerformed(evt);
            }
        });
        jPanel5.add(unlockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        homeButton2.setText("Home");
        homeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(homeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel10.setText("Your Account has been Locked !");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, -1));

        exceedMaxAttemptDialog.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 140));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(270, 155));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(400, 90));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkPinButton.setText("login");
        checkPinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPinButtonActionPerformed(evt);
            }
        });
        jPanel7.add(checkPinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, -1));

        pinField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinFieldMouseClicked(evt);
            }
        });
        pinField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pinFieldMouseMoved(evt);
            }
        });
        pinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinFieldActionPerformed(evt);
            }
        });
        pinField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinFieldKeyTyped(evt);
            }
        });
        jPanel7.add(pinField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, -1));

        jLabel7.setText("Pin <4 digits>");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 20));

        resetButton2.setText("Reset");
        resetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(resetButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel4.setText("Please verify yourself");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 20));

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel7.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel5.setText("Attempts Remaining : " + User.curUser.attempts);
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 20));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel8.setText("Welcome "+User.curUser.initials+" " + User.curUser.name+" !");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkPinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPinButtonActionPerformed
     
     if(User.curUser.attempts==0)
     {
         this.setVisible(false);
         exceedMaxAttemptDialog.setVisible(true);
     }
    else if(User.curUser.matchPin(User.encodePin(new String(pinField.getPassword()))))
      {
          if(User.curUser.attempts!=3)
                User.curUser.setAttempts(User.MAXATTEMPTS);
          
          this.dispose();
          new TransactionFrame().setVisible(true);
      }
     else
      {
          User.curUser.setAttempts(User.curUser.attempts-1);
          pwdIncorrectDialog.setVisible(true);
      }
      
    }//GEN-LAST:event_checkPinButtonActionPerformed

    private void pinFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldMouseClicked

    private void pinFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinFieldMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldMouseMoved

    private void pinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldActionPerformed

    private void resetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetButton2ActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void tryAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryAgainButtonActionPerformed
        pwdIncorrectDialog.dispose();
        this.dispose();
        new VerifyPwdFrame().setVisible(true);
    }//GEN-LAST:event_tryAgainButtonActionPerformed

    private void unlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockButtonActionPerformed
        this.dispose();
        exceedMaxAttemptDialog.setVisible(false);
        new ForgotFrame().setVisible(true);
    }//GEN-LAST:event_unlockButtonActionPerformed

    private void homeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButton2ActionPerformed
       this.dispose();
       exceedMaxAttemptDialog.setVisible(false);
       new LoginFrame().setVisible(true);
    }//GEN-LAST:event_homeButton2ActionPerformed

    private void pinFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinFieldKeyTyped
              char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }      
        
        else if(new String(pinField.getText()).length()==4)
        {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_pinFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifyPwdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifyPwdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifyPwdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifyPwdFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerifyPwdFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkPinButton;
    private javax.swing.JDialog exceedMaxAttemptDialog;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton homeButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JDialog pwdIncorrectDialog;
    private javax.swing.JButton resetButton2;
    private javax.swing.JButton tryAgainButton;
    private javax.swing.JButton unlockButton;
    // End of variables declaration//GEN-END:variables
}
