/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankinggui;

import javax.swing.JOptionPane;

/**
 *
 * @author fragger
 */
public class WithdrawlFrame extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawlFrame
     */
    public WithdrawlFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawlSuccessDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        withdrawlSuccessLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        withdrawlFailDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        withdrawlAmtField = new javax.swing.JTextField();
        withdrawButton = new javax.swing.JButton();

        withdrawlSuccessDialog.setAlwaysOnTop(true);
        withdrawlSuccessDialog.setLocationByPlatform(true);
        withdrawlSuccessDialog.setMinimumSize(new java.awt.Dimension(280, 190));
        withdrawlSuccessDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        withdrawlSuccessLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        withdrawlSuccessLabel.setText("You balance is now :      ");
        jPanel2.add(withdrawlSuccessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 20));

        jLabel4.setText("Withdrawl Done Successfully !");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        withdrawlSuccessDialog.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 150));

        withdrawlFailDialog.setAlwaysOnTop(true);
        withdrawlFailDialog.setLocationByPlatform(true);
        withdrawlFailDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel5.setText("Insufficient balance. Can't withdraw !");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 20));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        withdrawlFailDialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 150));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(274, 229));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setText("Withdrawl Form");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, 30));

        jLabel3.setText("Amount : ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 70, 20));

        withdrawlAmtField.setText("0");
        withdrawlAmtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                withdrawlAmtFieldMouseClicked(evt);
            }
        });
        withdrawlAmtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                withdrawlAmtFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                withdrawlAmtFieldKeyTyped(evt);
            }
        });
        jPanel3.add(withdrawlAmtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, -1));

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });
        jPanel3.add(withdrawButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawlAmtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_withdrawlAmtFieldMouseClicked
        withdrawlAmtField.setText("");
    }//GEN-LAST:event_withdrawlAmtFieldMouseClicked

    private void withdrawlAmtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdrawlAmtFieldKeyPressed

    }//GEN-LAST:event_withdrawlAmtFieldKeyPressed

    private void withdrawlAmtFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdrawlAmtFieldKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='0') && (c<='9') || (c==java.awt.event.KeyEvent.VK_BACK_SPACE) || (c==java.awt.event.KeyEvent.VK_DELETE)))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_withdrawlAmtFieldKeyTyped

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        if(Integer.parseInt(withdrawlAmtField.getText())<=0)
        {
            JOptionPane.showInputDialog(rootPane, "WARNING!","Please enter a valid amount !");
        }
        else
            {
            if(User.curUser.withdrawl(Integer.parseInt(new String(withdrawlAmtField.getText()))))
            {
            this.dispose();
            withdrawlSuccessLabel.setText("Your balance is now : "+User.curUser.getBal());
            withdrawlSuccessDialog.setVisible(true);    
            }
        
            else
            {
            this.dispose();
            withdrawlFailDialog.setVisible(true);
            }
        }
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        withdrawlSuccessDialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawlFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JTextField withdrawlAmtField;
    private javax.swing.JDialog withdrawlFailDialog;
    private javax.swing.JDialog withdrawlSuccessDialog;
    private javax.swing.JLabel withdrawlSuccessLabel;
    // End of variables declaration//GEN-END:variables
}
